application: mi-fi-monitor
version: 1
runtime: python
api_version: 1

handlers:

- url: /login.cgi
  script: main.py

- url: /getStatus.cgi
  script: main.py

- url: /modemstatus.html
  script: main.py

- url: .*
  script: main.py
